apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: morpheus-api-atlas
  namespace: morpheus-api-atlas
  labels:
    app: morpheus-api-atlas
spec:
  ingressClassName: traefik
  rules:
  - host: "morpheusatlas.init0xff.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: morpheus-api-atlas-svc
            port:
              number: 8743
