apiVersion: v1
kind: Service
metadata:
  name: morpheus-api-atlas-svc
  namespace: morpheus-api-atlas
  labels:
    app: morpheus-api-atlas
spec:
  selector:
    app: morpheus-api-atlas
  ports:
  - port: 8743
    targetPort: 2222
    protocol: TCP
